In [46]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

In [47]:
dataset = pd.read_csv("iris.data",header=None)
dataset

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [48]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.1,random_state=101)

In [49]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [50]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [51]:
model = Sequential()

model.add(Dense(4,input_shape=(4,), activation='relu'))

model.add(Dense(3, activation='softmax'))

In [52]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [53]:
model.fit(X_train, y_train, batch_size=10, epochs=150)

Epoch 1/150
135/135 [==============================] - 1s 5ms/step - loss: 2.6545 - accuracy: 0.3481
Epoch 2/150
135/135 [==============================] - 0s 272us/step - loss: 2.3836 - accuracy: 0.3481
Epoch 3/150
135/135 [==============================] - 0s 294us/step - loss: 2.1473 - accuracy: 0.3481
Epoch 4/150
135/135 [==============================] - 0s 366us/step - loss: 1.9290 - accuracy: 0.3481
Epoch 5/150
135/135 [==============================] - 0s 285us/step - loss: 1.7483 - accuracy: 0.3481
Epoch 6/150
135/135 [==============================] - 0s 300us/step - loss: 1.5909 - accuracy: 0.3481
Epoch 7/150
135/135 [==============================] - 0s 290us/step - loss: 1.4620 - accuracy: 0.3481
Epoch 8/150
135/135 [==============================] - 0s 297us/step - loss: 1.3556 - accuracy: 0.3481
Epoch 9/150
135/135 [==============================] - 0s 285us/step - loss: 1.2743 - accuracy: 0.3481
Epoch 10/150
135/135 [==============================] - 0s 299us/step - los

135/135 [==============================] - 0s 290us/step - loss: 0.5069 - accuracy: 0.9407
Epoch 80/150
135/135 [==============================] - 0s 346us/step - loss: 0.5024 - accuracy: 0.9556
Epoch 81/150
135/135 [==============================] - 0s 367us/step - loss: 0.4976 - accuracy: 0.9481
Epoch 82/150
135/135 [==============================] - 0s 343us/step - loss: 0.4939 - accuracy: 0.9111
Epoch 83/150
135/135 [==============================] - 0s 331us/step - loss: 0.4905 - accuracy: 0.9259
Epoch 84/150
135/135 [==============================] - 0s 277us/step - loss: 0.4860 - accuracy: 0.9333
Epoch 85/150
135/135 [==============================] - 0s 360us/step - loss: 0.4809 - accuracy: 0.9556
Epoch 86/150
135/135 [==============================] - 0s 389us/step - loss: 0.4771 - accuracy: 0.9556
Epoch 87/150
135/135 [==============================] - 0s 331us/step - loss: 0.4732 - accuracy: 0.9556
Epoch 88/150
135/135 [==============================] - 0s 313us/step - loss:

In [54]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [55]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.67      0.80         3
           2       0.86      1.00      0.92         6

    accuracy                           0.93        15
   macro avg       0.95      0.89      0.91        15
weighted avg       0.94      0.93      0.93        15

[[6 0 0]
 [0 2 1]
 [0 0 6]]
